### ISSUE TITLE
error with using senaite.patient

### ISSUE THREAD

**Issue by pathcoder4408** [senaite/senaite.patient#103]
on ubuntu 22 served with AWS.  Using apache2 as front end with reverse proxy
When I install senaite.patient the ability to add a sample becomes corruplt.   When i uninstall senaite.patient, the error behavior goes away.  See below,  On senaite lims 2.5 using plone5.2.14

We’re sorry, but there seems to be an error…
Here is the full error message:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 385, in publish_module
  Module ZPublisher.WSGIPublisher, line 288, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module bika.lims.browser.analysisrequest.add2, line 100, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 215, in render
  Module chameleon.template, line 192, in render
  Module dc0f670d3a90a51955e295c56d76099c, line 4446, in render
  Module 225403b8da6597328ab376539d007fba, line 1428, in render_master
  Module 225403b8da6597328ab376539d007fba, line 407, in render_content
  Module dc0f670d3a90a51955e295c56d76099c, line 2220, in __fill_content_core
  Module a9bc4fb7736298084ffbb4081002a3ab, line 1047, in render_edit
  Module zope.tales.pythonexpr, line 73, in __call__
   - __traceback_info__: (widget.attrs())
  Module <string>, line 1, in <module>
TypeError: attrs() takes exactly 3 arguments (1 given)

 - Expression: "python:widget.attrs()"
 - Filename:   ... /skins/templates/senaite_patient_widgets/agedobwidget.pt
 - Location:   (line 124: col 37)
 - Source:     tal:attributes="python:widget.attrs();
                               ^^^^^^^^^^^^^^^^^^^^^
 - Expression: "provider:plone.abovecontentbody"
 - Filename:   ... te/core/browser/main_template/templates/main_template.pt
 - Location:   (line 132: col 84)
 - Source:     ... 
                                     ^
 - Expression: "here/main_template/macros/master"
 - Filename:   ... g/bika/lims/browser/analysisrequest/templates/ar_add2.pt
 - Location:   (line 4: col 23)
 - Source:     metal:use-macro="here/main_template/macros/master"
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  request: <WSGIRequest, URL=http://xxx.xx.xxx/senaite/samples/ar_add>
               attrs: {}
               container: <Samples at /senaite/samples>
               traverse_subpath: []
               template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7faaa8ecd190>
               translate: <function translate at 0x7faa973f6ed0>
               macroname: u'master'
               repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7faaa67681e0>
               views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7faa97c52810>
               args: ()
               here: <Samples at /senaite/samples>
               user: <PropertiedUser 'admin'>
               nothing: None
               default: <DEFAULT>
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7faab4d50c90>
               loop: {u'field': <Products.PageTemplates.engine.RepeatItem object at 0x7faa971e2b90>, u'record': <Products.PageTemplates.engine.RepeatItem object at 0x7faa96cedd10>, u'arnum': <Products.PageTemplates.engine.RepeatItem object at 0x7faa96c1fb10>, u'item': <Products.PageTemplates.engine.RepeatItem object at 0x7faa9707c450>}
               context: <Samples at /senaite/samples>
               view: <Products.Five.browser.metaconfigure.AnalysisRequestAddView object at 0x7faa97a7b190>
               root: <Application at >
               options: {}
               target_language: None

**Comment by xispa** [comment]
@pathcoder4408 ,this gets fixed with [senaite.patient 1.4.0](https://pypi.org/project/senaite.patient/1.4.0/), that we have just released. Please re-run `bin/buildout` to download latest version.

**Comment by ramonski** [comment]
Closing for now.
Please reopen if you still encounter this issue with the newest version.
Thanks
