### ISSUE TITLE
Add Patient results in traceback

### ISSUE THREAD

**Issue by ronna** [senaite/senaite.patient#16]
Running the lastest senaite.core and senaite.patient from master, adding new patient results in Traceback

We’re sorry, but there seems to be an error…
Here is the full error message:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module plone.z3cform.layout, line 63, in __call__
  Module plone.z3cform.layout, line 57, in update
  Module z3c.form.form, line 281, in render
  Module z3c.form.form, line 162, in render
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 192, in render
  Module aef580ec245661827ce6878a068c8adc, line 115, in render
  Module 64180cf16800a708fa4fc13a2a55c821, line 2201, in render_titlelessform
  Module 64180cf16800a708fa4fc13a2a55c821, line 424, in render_fields
  Module 64180cf16800a708fa4fc13a2a55c821, line 150, in render_widget_rendering
  Module 64180cf16800a708fa4fc13a2a55c821, line 1022, in render_field
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 196, in _eval
  Module Products.PageTemplates.Expressions, line 126, in render
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 81, in __call__
  Module zope.browserpage.viewpagetemplatefile, line 49, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 214, in render
  Module chameleon.template, line 192, in render
  Module 1fa0ccc88213050dc52d547b0963c722, line 586, in render
  Module 1fa0ccc88213050dc52d547b0963c722, line 456, in render_widget_wrapper
  Module zope.tales.expressions, line 250, in __call__
  Module Products.PageTemplates.Expressions, line 196, in _eval
  Module Products.PageTemplates.Expressions, line 126, in render
  Module plone.app.z3cform.widget, line 180, in render
  Module plone.app.z3cform.widget, line 117, in render
  Module plone.app.z3cform.widget, line 231, in _base_args
  Module plone.app.z3cform.widget, line 168, in _base_args
  Module plone.app.widgets.utils, line 41, in get_date_options
AttributeError: 'str' object has no attribute 'dates'

 - Expression: "widget/render"
 - Filename:   ... e/src/senaite/core/browser/dexterity/templates/widget.pt
 - Location:   (line 41: col 32)
 - Source:     tal:replace="structure widget/render"
                                      ^^^^^^^^^^^^^
 - Expression: "widget/@@ploneform-render-widget"
 - Filename:   ... e/src/senaite/core/browser/dexterity/templates/macros.pt
 - Location:   (line 149: col 61)
 - Source:     ... place="structure widget/@@ploneform-render-widget"/>
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "context/@@ploneform-macros/titlelessform"
 - Filename:   ... 1.3-py2.7.egg/plone/z3cform/pagetemplates/wrappedform.pt
 - Location:   (line 1: col 22)
 - Source:     ... e use-macro="context/@@ploneform-macros/titlelessform" />
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7fd6b607e3c0>
               context: <DatetimeWidget 'form.widgets.birthdate'>
               views: <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x7fd6a741a990>
               modules: <zope.pagetemplate.engine.TraversableModuleImporter object at 0x7fd6c2fbcd50>
               args: ()
               nothing: None
               target_language: None
               default: <DEFAULT>
               request: <WSGIRequest, URL=http://localhost:8080/senaite3/patients/++add++Patient>
               loop: {}
               template: <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x7fd6b6b88790>
               translate: <function translate at 0x7fd6b76df9d0>
               options: {}
               view: <Products.Five.browser.metaconfigure.SenaiteRenderWidget object at 0x7fd6a741a310>

**Additional Information**

**Version Overview**
Plone 5.2.4 (5212)
CMF 2.5.0
Zope 4.5.5
Python 2.7.18 (default, Mar 8 2021, 13:02:45) [GCC 9.3.0]
PIL 6.2.2 (Pillow)
WSGI: On
Server: waitress 1.4.4

**(senaite) senaite@tux:~/patient/src/senaite.core$ git log**
commit e27b542b40e58917b20e7210132841c13e2d13de (HEAD -> 2.x, origin/HEAD, origin/2.x)
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Wed Nov 17 17:13:56 2021 +0100

    Fix two dimension results parser for Analyses containing a dash in the name (#1878)
    
    * Fix two dimension results parser
    
    Allow analysis keywords containing minus, plus and dots
    
    * Updated changelog

commit cc8570f796e90c724f06fecd02cf65332b45cdaa
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Wed Nov 17 15:55:33 2021 +0100

    Fix missing catalog mappings after migration (#1877)

commit 4f54baa3b9a3cd51b089f2e6f96bc0cd5e9f5f4b
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Tue Nov 16 09:57:00 2021 +0100

**(senaite) senaite@tux:~/patient/src/senaite.patient$ git log**
commit 4852c65205282945448af2a667cee23463c20266 (HEAD -> master, origin/master, origin/HEAD)
Merge: 13513ce dd29d94
Author: Ramon Bartl <rb@ridingbytes.com>
Date:   Wed Nov 17 11:56:11 2021 +0100

    Merge pull request #15 from senaite/first-last-name
    
    Support first name and last name, as well as fullname

commit dd29d942618a404c6f04131c9cb7fa58dc441f76
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Tue Nov 16 16:37:15 2021 +0100

    Support for dynamic edit mode of patient name entry

commit 1a54e12ffece031cc6d1b2f2be37a1b944238220
Author: Jordi Puiggené <jp@naralabs.com>
Date:   Tue Nov 16 16:20:15 2021 +0100

    Upgrade step

**Comment by ramonski** [comment]
Hi @ronna,
does this happen in a new Senaite site?
Maybe you have forgotten to run the migration steps?

**Comment by ronna** [comment]
Hi @ramonski 
There are no upgrades when I navigate to http://localhost:8080/senaite3/portal_setup/manage_upgrades

I got the below error from my other site and created a new site. The below error I am sure was introduced by [](https://github.com/senaite/senaite.core/pull/1872)  and I could not find the upgrade again

error while rendering bika.lims.instrument_qc_failures_viewlet
We’re sorry, but there seems to be an error…
Here is the full error message:

Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 371, in publish_module
  Module ZPublisher.WSGIPublisher, line 274, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 63, in call_object
  Module senaite.core.browser.dashboard.dashboard, line 211, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 378, in __call__
  Module z3c.pt.pagetemplate, line 176, in render
  Module chameleon.zpt.template, line 302, in render
  Module chameleon.template, line 214, in render
  Module chameleon.template, line 192, in render
  Module 7a9dc8edf4e3f61274472a10a970dec9, line 1705, in render
  Module 19e9a660b82519f5ef920579fb34982a, line 1449, in render_master
  Module 19e9a660b82519f5ef920579fb34982a, line 407, in render_content
  Module 7a9dc8edf4e3f61274472a10a970dec9, line 248, in __fill_content_core
  Module zope.tales.pythonexpr, line 73, in __call__
   - __traceback_info__: (view.get_sections())
  Module <string>, line 1, in <module>
  Module senaite.core.browser.dashboard.dashboard, line 344, in get_sections
  Module senaite.core.browser.dashboard.dashboard, line 538, in get_analyses_section
  Module Products.CMFCore.utils, line 13, in check_getToolByName
  Module Products.CMFCore.utils, line 139, in getToolByName
AttributeError: senaite_catalog_analysis

 - Expression: "provider:plone.abovecontentbody"
 - Filename:   ... te/core/browser/main_template/templates/main_template.pt
 - Location:   (line 136: col 84)
 - Source:     ... 
                                     ^
 - Expression: "here/main_template/macros/master"
 - Filename:   ... rc/senaite/core/browser/dashboard/templates/dashboard.pt
 - Location:   (line 2: col 23)
 - Source:     metal:use-macro="here/main_template/macros/master"
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7fc2d42d22d0>
               template: <Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at 0x7fc2d4ed6310>
               views: <Products.Five.browser.pagetemplatefile.ViewMapper object at 0x7fc2d1b19950>
               request: <WSGIRequest, URL=http://localhost:8080/senaite2/senaite-dashboard>
               args: ()
               here: <PloneSite at /senaite2>
               user: <PropertiedUser 'admin'>
               nothing: None
               root: <Application at >
               translate: <function translate at 0x7fc2d1bf77d0>
               container: <PloneSite at /senaite2>
               macroname: u'master'
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7fc2e13c2c90>
               traverse_subpath: []
               default: <DEFAULT>
               loop: {}
               context: <PloneSite at /senaite2>
               view: <Products.Five.browser.metaconfigure.DashboardView object at 0x7fc2d1b7e550>
               target_language: None
               attrs: {}
               options: {}

**Comment by ramonski** [comment]
Hi @ronna,
you need to click on the "Show old upgrades" button and re-run 2.0.1 for `senaite.core` and `1.0.0` for `senaite.patient` again

<img width="763" alt="Add-on and configuration management 2021-11-18 19-19-28" src="https://user-images.githubusercontent.com/713193/142473777-26572497-fef8-4775-99f4-362c82fff88e.png">

<img width="878" alt="Add-on and configuration management 2021-11-18 19-20-06" src="https://user-images.githubusercontent.com/713193/142473860-2d47023d-a712-4b1d-9983-7efcd77de900.png">

**Comment by ronna** [comment]
@ramonski thanks that worked. Chrome cache was fighting me after the upgrade step
