### ISSUE TITLE
Client can see patients from other client

### ISSUE THREAD

**Issue by erikking** [senaite/senaite.patient#73]
## Steps to reproduce and Current behavior

We have multiple clients with contact (account set up), and when client account login, the client can see all patients (from current client and other client) in patient section. 

## Expected behavior

The client account can only see its own patients.

**Comment by ramonski** [comment]
Hi @erikking,

This issue has been already addressed in https://github.com/senaite/senaite.patient/pull/69 and https://github.com/senaite/senaite.core/pull/2301 and will be part of the upcoming versions.

Please note, that with https://github.com/senaite/senaite.patient/pull/68 you can now also create client local patients. This makes it sure that these patients are isolated to the client and the client contacts.

**Comment by erikking** [comment]
Thanks for your quick response.

Exciting to see incoming release to address the feature.

**Comment by ramonski** [comment]
Closing this one for now.
Please feel free to reopen if it is still an issue for the upcoming version 1.4.0.
Thanks.
